services:
  _defaults:
    autoconfigure: true

  Mindbird\ContaoUiToTop\FrontendModule\UiToTopFrontendModuleController:
    autoconfigure: true
    arguments:
      $scopeMatcher: '@contao.routing.scope_matcher'